import "./globals.css";
//Context
import MainLayout from "./layout/layout";
import { AuthProvider } from "@/context/AuthContext";
import { ConfirmProvider } from "@/context/ConfirmProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased">
        <AuthProvider>
          <ConfirmProvider>
            <MainLayout>{children}</MainLayout>
          </ConfirmProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
